<?php
/**
 * Implements hook_menu().
 */
function canvas_menu() {
  $items = array();
  $items['canvas/%/like'] = array(
    'page callback' => 'canvas_like',
    'access callback' => TRUE,
  );
  $items['canvas/%/oauth'] = array(
    'page callback' => 'canvas_oauth',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function canvas_theme() {
  return array(
    'canvas_like' => array(
      'template' => 'canvas_like',
    ),
  );
}

/**
 * Redirect to oauth dialog.
 */
function canvas_oauth() {
  $facebook = canvas_api();
  return "<p>" . $facebook->getLoginUrl(). "</p>";
}

/**
 * Page Callback for Like Requests.
 */
function canvas_like() {
  $facebook = canvas_api();
  $content = array();
  try {
    $sr = $facebook->getSignedRequest();
  }
  catch (Exception $exc) {
  }
  if ($sr && array_key_exists('page', $sr)) {
    $page_url = FALSE;
    if (array_key_exists('page', $sr)) {
      $data = drupal_json_decode(drupal_http_request('http://graph.facebook.com/' . $sr['page']['id'])->data);
      $page_url = $data['link'];
    }
    if ($page_url) {
      $content['button'] = array(
        '#theme' => 'html_tag',
        '#tag' => 'fb:like',
        '#value' => '&nbsp;',
        '#attributes' => array(
          'href' => $page_url,
          'show_faces' => 'false',
          'layout' => 'button_count',
          'send' => 'false',
        ),
      );
      if (array_key_exists('next', $_REQUEST)) {
        drupal_add_js('jQuery(document).ready(function () {
          FB.Event.subscribe("edge.create", function(response) {
            top.location.href = "' . $page_url . '?sk=app_' . $facebook->appid . '";
          });
        });', array('type' => 'inline', 'scope' => 'footer', 'weight' => 5));
      }
    }
  }
  return theme('canvas_like', $content);
}

/**
 * Return all implemented Facebook Apps.
 */
function canvas_get_apps() {
  $apps = &drupal_static(__FUNCTION__);
  if (!isset($apps)) {
    $apps = module_invoke_all('canvas_apps');
    drupal_alter('canvas_apps', $apps);
  }
  return $apps;
}

/**
 * Implements hook_init().
 */
function canvas_init() {
  $item = menu_get_item($_GET['q']);
  if ($item['access_callback'] == 'canvas_likes') {
    if (!canvas_likes()) {
      drupal_goto('canvas/' . arg(0) . '/like', array(
        'query' => array('next' => $_GET['q']),
      ));
    }
  }
  $facebook = canvas_api();
  if ($facebook) {
    drupal_add_js('https://connect.facebook.net/' . $facebook->language . '/all.js', array('type' => 'external'));
    drupal_add_js(drupal_get_path('module', 'canvas') . '/canvas.js');
    drupal_add_css(drupal_get_path('module', 'canvas') . '/canvas.css');
    drupal_add_js(array('canvas' => array('appid' => $facebook->appid)), 'setting');
  }
}

/**
 * Initializes a facebook api object from the apps-array.
 */
function canvas_api($app = FALSE) {
  if (!$app) {
    $app = arg(0);
  }
  if ($app == 'canvas') {
    $app = arg(1);
  }
  $api = &drupal_static(__FUNCTION__);
  if (isset($api)) {
    return $api;
  }
  $apps = canvas_get_apps();
  if (!array_key_exists($app, $apps)) {
    return FALSE;
  }
  require_once 'facebook.php';
  try {
    $api = new Facebook(array(
      'appId' => $apps[$app]['appid'],
      'secret' => $apps[$app]['secret'],
      'cookie' => TRUE,
    ));
    $api->path_prefix = $app;
    $api->appid = $apps[$app]['appid'];
    $api->theme = $apps[$app]['theme'];
    $api->language = $apps[$app]['language'];
    return $api;
  }
  catch (Exception $exc) {
    dpm($exc);
  }
  return FALSE;
}

/**
 * Implements hook_form_alter().
 * Pass signed request to form calls.
 */
function canvas_form_alter(&$form, &$form_state) {
  if (!array_key_exists('signed_request', $form) && array_key_exists('signed_request', $_REQUEST)) {
    $form['signed_request'] = array(
      '#type' => 'hidden',
      '#value' => $_REQUEST['signed_request'],
    );
  }
}

/**
 * Implements hook_url_outbound_alter().
 * Pass signed requests to urls.
 */
function canvas_url_outbound_alter(&$path, &$options, $original_path) {
  if (array_key_exists('signed_request', $_REQUEST)) {
    $options['query']['signed_request'] = $_REQUEST['signed_request'];
  }
}

/**
 * Check if user authorized page.
 */
function canvas_authorized() {
  $facebook = canvas_api();
  if (!$facebook) {
    return FALSE;
  }
  try {
    $me = $facebook->api('/me');
  }
  catch (Exception $exc) {
    $me = FALSE;
  }
  if ($me) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}

/**
 * Check if the user likes the page.
 */
function canvas_likes() {
  if($facebook = canvas_api()) {
    $data = array();
    try {
      $data = $facebook->getSignedRequest();
    }
    catch (Exception $exc) {
      dpm($exc->getMessage());
    }
    if (array_key_exists('page', $data) && $data['page']['liked']) {
      return TRUE;
    }
    else {
      return FALSE;
    }
  }
  else {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_custom_theme().
 */
function canvas_custom_theme() {
  if ($facebook = canvas_api()) {
    return $facebook->theme;
  }
}
